### ISSUE TITLE
Documentation clarification.

### ISSUE THREAD

**Issue by s-archer** [F5Networks/f5-bigip-runtime-init#1]
In the root readme.md, can you clarify what "Any declarations containing ``````" means please?

**Comment by mikeshimkus** [comment]
Hi, yes, this is a typo and should read: "Any declarations containing ```{{ADMIN_PASS}}```"

We'll be correcting this shortly.

**Comment by shyawnkarim** [comment]
Closing.

This correction to our documentation was included with [Release 1.1.0](https://github.com/F5Networks/f5-bigip-runtime-init/releases/tag/1.1.0).
