### ISSUE TITLE
Collect AWS IPv4 info - erroring metadata

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-bigip-runtime-init#22]
I'm trying to find IPs assigned to the VM instance via runtime parameters metadata. I do not see anything specific in the README. I checked the config and examples folder, and there is an example with Azure. I grabbed it, changed cloud to AWS but I get errors.

I need this...
  - name: SELF_IP_EXTERNAL
    type: metadata
    metadataProvider:
      environment: aws
      type: network
      field: ipv4
      index: 1

I get this error when I try to run it...
2021-08-03T21:08:11.765Z [21114]: info: Validating provided declaration
2021-08-03T21:08:11.818Z [21114]: error: Invalid declaration: "data.runtime_parameters[1].metadataProvider.field should be equal to one of the allowed values, data.runtime_parameters[1].metadataProvider should match \"then\" schema"

Use case:
I want to collect the IP, then assign it as self IP similar to the Azure example in this yaml file.
https://github.com/F5Networks/f5-bigip-runtime-init/blob/main/examples/config/cloud_config_local_w_as3_w_runtime_param.yaml

**Comment by JeffGiroux** [comment]
I think I found the right example. Also, docs need updating. These parameter metadata fields are hard to find in this repo. Other than looking at example folder, it is not documented which things are supported or not. If I missed it, please provide the link. 

I will test this. https://github.com/F5Networks/f5-bigip-runtime-init/blob/main/examples/config/example_6.yaml

  - name: SELF_IP_EXTERNAL
    type: metadata
    metadataProvider:
      environment: aws
      type: network
      field: local-ipv4s
      index: 1


It appears the Azure field and AWS field for IPv4 differ. Why can't they be the same? The only thing that should need to change is the environment. I should NOT have to know to use local-ipv4s for AWS and ipv4 for Azure.

**Comment by JeffGiroux** [comment]
I tested and am able to successfully pull the IPv4 with correct field.

My suggestion still stands for doc updates and clearly identifying all the possible metadata cloud provider values that are accessible each big-ip runtime init release.

Also, I'm running into an issue where self IP as a virtual cannot be a mask. The IPv4 field in AWS pulls down the IP/mask and I cannot have the mask included. I will add my comments to existing issue in https://github.com/F5Networks/f5-bigip-runtime-init/issues/20.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. I agree that trying to hunt down that info and then not having consistency between Azure and AWS is confusing. We are now tracking this with internal ID ESECLDTPLT-2826.

**Comment by JeffGiroux** [comment]
I just discovered during lots of pain and suffering that google requires a different value too!!!!

```
field: ipv4
```

**Comment by shyawnkarim** [comment]
Closing. The examples can be used as documentation and we do surface those runtime parameters here:

https://github.com/F5Networks/f5-bigip-runtime-init#runtime_parameters
