### ISSUE TITLE
Retrieve Azure IP without mask

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-bigip-runtime-init#25]
Currently the network block yaml to retrieve Azure network info retrieve IP/mask. This is similar to the AWS github issue here - https://github.com/F5Networks/f5-bigip-runtime-init/issues/20

This works for assigning self IPs which take IP/mask. However, there are other places in my onboarding that require IP only like CFE self IP tags, maybe DSC cluster remote IP. The declarations will fail if they have mask, and there is no way to remove mask from IP within the runtime init yaml during processing. It must occur outside.

Requesting that the IP block yaml for Azure metadata return options for both IP and mask separate. Preferrably, there is an option like ipcalc first that gives the first IP. Looking for similar to give:

- IP/mask
- IP only
- mask only

**Comment by JeffGiroux** [comment]
Is anyone looking at this. It seems IPcalc has this function and that the ipcalc 'address' will give me what I want. I will test. However I think for documentation purposes the runtime_parameters.yaml example file should be more noticeable on the README page. Will test ipcalc 'address' and report back.

**Comment by shyawnkarim** [comment]
Yes, ipcalc 'address' will work for this use case. In addition, ipcalc also provides the following transformation options:

address - The provided address without netmask prefix.
base - The base address of the network block as a string (eg: 216.240.32.0). Base does not give an indication of the size of the network block.
mask - The netmask as a string (eg: 255.255.255.0).
hostmask - The host mask which is the opposite of the netmask (eg: 0.0.0.255).
bitmask - The netmask as a number of bits in the network portion of the address for this block (eg: 24).
size - The number of IP addresses in a block (eg: 256).
broadcast - The blocks broadcast address (eg: 192.168.1.0/24 => 192.168.1.255).
first - First useable address.
last - Last useable address.

[Link to full documentation.](https://github.com/F5Networks/f5-bigip-runtime-init#runtime-parameters)

**Comment by shyawnkarim** [comment]
Closing. Please reopen if needed.
