### ISSUE TITLE
Hashicorp Vault: Namespace is required for appRole Login

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-bigip-runtime-init#30]
In issue https://github.com/F5Networks/f5-bigip-runtime-init/issues/14, you stated

> Regarding namespace: we decided not use X-Vault-Namespace header and instead of, we allow providing namespace value as part of secretPath field

Our tests show that the appRole login without providing a Namespace doesn't work for us. Indeed, without providing explicitely a namespace, it defaults to "root". The customer's Vault has been setup in a (secure) way that each Namespace is an "administrative compartment". If I specify Namespace in the header here: https://github.com/F5Networks/f5-bigip-runtime-init/blob/ddf3f75dd672894cbd4bcc1d1d4b15083c2a4a98/src/lib/provider/secret/hashicorpVaultClient.ts#L60
it works as expected.
The customer told me that if, same as for the secret path, we would prefix the appRole login with the namespace, it would also work, such as `/v1/<namespace>/auth/approle/login`

**Comment by mikeshimkus** [comment]
Hi, I created issue #2884 to track this work.

**Comment by mikeshimkus** [comment]
@amolari Following the current model we use for the secretId, would it be sufficient to allow setting the approle login URL? That way namespace (and custom approle path, if used) could be specified?

**Comment by amolari** [comment]
@mikeshimkus Yes, it would be sufficient to allow setting the approle login URL

**Comment by shyawnkarim** [comment]
Closing. This was included with [Release 1.4.0](https://github.com/F5Networks/f5-bigip-runtime-init/releases/tag/1.4.0).
