### ISSUE TITLE
RFE - Log runtime-init success/failure externally

### ISSUE THREAD

**Issue by mwardbopp** [F5Networks/f5-bigip-runtime-init#39]
When running in AWS via a CFT or similar pipeline there is no way to know the status/failures of runtime-init, either during the boot up or if it fails. It a minimum it would be great to have the output of the runtimelog in the CFT failure.

**Comment by mwardbopp** [comment]
Actually the runtime init is logged in AWS instance system log. It would be great if a snapshot of those logs could be sent to CFT if there is a failure.

**Comment by shyawnkarim** [comment]
Thanks for submitting this request. We are now tracking this enhancement internally with ID ESECLDTPLT-3077.

**Comment by shyawnkarim** [comment]
Closing due to age. Enabling this is not trivial and the Runtime-Init documentation has a good troubleshooting section.
