### ISSUE TITLE
F5 VM onboarding is failing with error "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by KodiakF5Team** [F5Networks/f5-bigip-runtime-init#48]
F5 VM was created through arm v2 template converted to bicep.
sometimes onboarding is failing with mentioned error 
Cannot read property 'length' of undefined
,and when tried multiple time ,it is not getting resolve

command executed :- 
 f5-bigip-runtime-init --config-file /config/cloud/runtime-init.txt
F5 Version:- 15.1.6.1
[runtime-init.txt](https://github.com/F5Networks/f5-bigip-runtime-init/files/9547436/runtime-init.txt)

**Comment by KodiakF5Team** [comment]
[waagent.txt](https://github.com/F5Networks/f5-bigip-runtime-init/files/9547454/waagent.txt)

**Comment by mikeshimkus** [comment]
@KodiakF5Team Hi, please provide the output of /var/log/cloud/bigIpRuntimeInit.log. If you can retry after setting controls.logLevel to "silly", that would be helpful.

Also, which version of Runtime Init are you using? Does it work when deploying the ARM template prior to converting to bicep?
thanks

**Comment by KodiakF5Team** [comment]
[bigIpRuntimeInit.txt](https://github.com/F5Networks/f5-bigip-runtime-init/files/9554366/bigIpRuntimeInit.txt)
@mikeshimkus 
Hi Mike ,

attaching the bigIpRuntimeInit.log after setting to silly. 
for Runtime Init version not sure , but may be 1.4.0 we are using.
it is working intermittently

**Comment by KodiakF5Team** [comment]
@mikeshimkus 
Hi Mike,
Thanks for responding. i have modified the runtime-init.conf to latest.
After making the changes to 1.5.1 still I am still seeing same error log.
attaching the bigIpRuntimeInit.log and runtime-init.conf file
[bigIpRuntimeInit.txt](https://github.com/F5Networks/f5-bigip-runtime-init/files/9564086/bigIpRuntimeInit.txt)
[runtime-init.txt](https://github.com/F5Networks/f5-bigip-runtime-init/files/9564108/runtime-init.txt)

**Comment by KodiakF5Team** [comment]
Hi

below is issue decrption

after changing to 1.5.1 , tried again and failed with same error (cannot read length) .issue was due to f5-bigip-runtime-init-1.5.1-1.gz.run was not updated to latest.
after updating to latest it his to another issue "Installation of fast failed because RPM hash is not valid"
after correcting the has to below , we are able to proceed,
    - extensionType: fast
      extensionVersion: 1.19.0
      extensionHash: d36ecbf05b997f214c2ab4883a52705aa41fbff9c1d8a11577072921eb3e42c7

**Comment by KodiakF5Team** [comment]
Hi @mikeshimkus 

we have downloaded the fast rpm locally and calculated the hash using below command

# sha256sum f5-appsvcs-templates-1.19.0-1.noarch.rpm
d36ecbf05b997f214c2ab4883a52705aa41fbff9c1d8a11577072921eb3e42c7  f5-appsvcs-templates-1.19.0-1.noarch.rpm

and in code it was 
 - extensionType: fast
      extensionVersion: 1.19.0
      extensionHash: 981b00b61c3dfc3d13f9e96836b6260aa250dc4b92fc7cb746b7ca7b2dbcea1d

after changing to correct hash (d36ecbf05b997f214c2ab4883a52705aa41fbff9c1d8a11577072921eb3e42c7) it worked fine.

**Comment by mikeshimkus** [comment]
I see, it appears you were using the hash value from the example in this repository. 

The Azure repository has the correct hash: https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/9a977c99267a6daf874b4494b430a7c33878d78b/examples/quickstart/bigip-configurations/runtime-init-conf-3nic-payg.yaml#L68. Please use this as a reference for now.

I created internal issue #3184 to fix this.

**Comment by KodiakF5Team** [comment]
Thanks @mikeshimkus  for support, It resolved the issue.

**Comment by KodiakF5Team** [comment]
Closing as after changing hash it worked Fine.
