### ISSUE TITLE
Deployments not working with version": "16.1.403000

### ISSUE THREAD

**Issue by cmgksims** [F5Networks/f5-bigip-runtime-init#62]
When trying to run a DO deployment with a version": "16.1.403000 my f5s will not pull a license from my bigiq. This used to work without any change. 
![image](https://github.com/F5Networks/f5-bigip-runtime-init/assets/164074711/f158267a-21f0-4746-966a-daac71bd0510)

**Comment by mikeshimkus** [comment]
@cmgksims Can you share the entire output of the runtime init logs, as well as the runtime init config YAML you used. If you are using a template, please share the template name, version, and input parameters (all sanitized). 
thanks

**Comment by cmgksims** [comment]
[f5init.log](https://github.com/user-attachments/files/16181957/f5init.log)
[custom.tmpl.log](https://github.com/user-attachments/files/16182150/custom.tmpl.log)


INIT_URL  = "https://cdn.f5.com/product/cloudsolutions/f5-bigip-runtime-init/v2.0.3/dist/f5-bigip-runtime-init-2.0.3-1.gz.run"
DO_URL   = "https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.44.0/f5-declarative-onboarding-1.44.0-5.noarch.rpm"
AS3_URL  = "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.51.0/f5-appsvcs-3.51.0-5.noarch.rpm"
TS_URL    = "https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.35.0/f5-telemetry-1.35.0-1.noarch.rpm"

**Comment by cmgksims** [comment]
The version I ran this same config on and it worked was on version 16.1.303000

**Comment by mikeshimkus** [comment]
Your error log shows an unsupported value for the Provision class:

`2024-07-11T18:10:27.818Z [8886]: error: {"id":"b8a1d136-a78e-42ca-8150-2912427eb954","selfLink":"https://localhost/mgmt/shared/declarative-onboarding/task/b8a1d136-a78e-42ca-8150-2912427eb954","code":400,"status":"ERROR","message":"bad declaration","errors":[{"keyword":"enum","dataPath":".declaration.Common['myProvisioning']","schemaPath":"#/allOf/3/then/propertyNames/enum","params":{"allowedValues":["class","afm","am","apm","asm","avr","cgnat","dos","fps","gtm","ilx","lc","ltm","pem","swg","urldb","sslo"]},"message":"should be equal to one of the allowed values","propertyName":"iruleslx"},{"keyword":"propertyNames","dataPath":".declaration.Common['myProvisioning']","schemaPath":"#/allOf/3/then/propertyNames","params":{"propertyName":"iruleslx"},"message":"property name 'iruleslx' is invalid"},{"keyword":"if","dataPath":"","schemaPath":"#/allOf/1/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"}],"result":{"class":"Result","code":400,"status":"ERROR","message":"bad declaration","errors":[{"keyword":"enum","dataPath":".declaration.Common['myProvisioning']","schemaPath":"#/allOf/3/then/propertyNames/enum","params":{"allowedValues":["class","afm","am","apm","asm","avr","cgnat","dos","fps","gtm","ilx","lc","ltm","pem","swg","urldb","sslo"]},"message":"should be equal to one of the allowed values","propertyName":"iruleslx"},{"keyword":"propertyNames","dataPath":".declaration.Common['myProvisioning']","schemaPath":"#/allOf/3/then/propertyNames","params":{"propertyName":"iruleslx"},"message":"property name 'iruleslx' is invalid"},{"keyword":"if","dataPath":"","schemaPath":"#/allOf/1/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"}]},"declaration":{"schemaVersion":"1.44.0","class":"Device","async":true,"label":"Onboard BIG-IP into Standalone Configuration","Common":{sanitized}}}}`

Here's the schema for DO 1.44.0: https://github.com/F5Networks/f5-declarative-onboarding/blob/574f8bef34f6599bdd64a468dd4aa32ca1da54eb/src/schema/1.44.0/system.schema.json#L93

I recommend opening an issue in the DO project if you think this is incorrect: https://github.com/F5Networks/f5-declarative-onboarding/issues

**Comment by cmgksims** [comment]
yea i had actually fixed that.  It was still failing before i had changed that as well. So i fixed that and ran it again and still failing. The previous version i was using is https://cdn.f5.com/product/cloudsolutions/f5-bigip-runtime-init/v1.5.1/dist/f5-bigip-runtime-init-1.5.1-1.gz.run but that did not work once i updated to the new bigip version 16.1.4

**Comment by cmgksims** [comment]
[bigIpRuntimeInit.log](https://github.com/user-attachments/files/16188965/bigIpRuntimeInit.log)

**Comment by cmgksims** [comment]
Latest deployment with everything using latest versions. 
[f5init.log](https://github.com/user-attachments/files/16194999/f5init.log)

**Comment by mikeshimkus** [comment]
Here it looks like you are failing to install Telemetry Streaming:

```shell
2024-07-12T05:10:26.418Z [10075]: silly: Request response: 200 {"packageFilePath":"/var/config/rest/downloads/f5-telemetry-1.33.0-1.noarch.rpm","operation":"INSTALL","id":"07f5c7de-fa6a-41e1-b209-8458b9d2a408","status":"STARTED","startTime":"2024-07-11T22:10:02.767-0700","userReference":{"link":"https://localhost/mgmt/shared/authz/users/admin"},"identityReferences":[{"link":"https://localhost/mgmt/shared/authz/users/admin"}],"ownerMachineId":"adcc7ffa-1d57-47e9-b61e-bfaae9c5dbb9","generation":2,"lastUpdateMicros":1720761002767295,"kind":"shared:iapp:package-management-tasks:iapppackagemanagementtaskstate","selfLink":"https://localhost/mgmt/shared/iapp/package-management-tasks/07f5c7de-fa6a-41e1-b209-8458b9d2a408"}
2024-07-12T05:10:27.970Z [10075]: error: Max count exceeded, last response: undefined
```

That is most likely due to the required iControl LX sys db variables not being set, and also possibly using an instance size that is too small. Check our our templates for the current example that sets the db variables: https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/64802083a592ba10e1f0854b5155cef74568f65a/examples/modules/bigip-standalone/bigip.json#L254

I believe these variables did change between 16.1.3 and 16.1.4. For maximum chance of success, I recommend you use our templates to deploy...you can still provide custom Runtime Init configuration using the template input parameters.

**Comment by cmgksims** [comment]
I had removed the ilx from provisioning even tried removing telemetry streaming from being downloaded and still no avail.  Here is my template file sanitized. I'm also using the Standard_F32s_v2 azure vm. 
[custom copy.tmpl.log](https://github.com/user-attachments/files/16198550/custom.copy.tmpl.log)

**Comment by mikeshimkus** [comment]
The updated sys db variables are in the wrong place in your script, they need to be right after this line:

```shell
# Run Immediately Before MCPD
```

Adding them to the DO config has no effect since they need to be set before MCPD starts.

Also, we have not tested Runtime Init with that instance type or size.

**Comment by cmgksims** [comment]
that fixed it moving those values out of the script
