### ISSUE TITLE
FAST support for Extension Packages

### ISSUE THREAD

**Issue by codygreen** [F5Networks/f5-bigip-runtime-init#9]
Add native support to the schema for the FAST package versus having to install as an iControl LX package.  This would mimic the behavior of other ATC components and makes the user experience more cohesive.   

FAST is a fully supported F5 ATC component and should have the same install experience as the other components. 

https://github.com/F5Networks/f5-bigip-runtime-init/blob/9c5bc96b90822efee60dfa13c056ca0011c92d7f/src/schema/base_schema.json#L193

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this enhancement internally with ID ESECLDTPLT-2445.

**Comment by codygreen** [comment]
@shyawnkarim, it looks like this has been addressed.  Can you please verify if this ticket can be closed?

**Comment by shyawnkarim** [comment]
Closing. 

Support for this was included with [Release 1.2.1](https://github.com/F5Networks/f5-bigip-runtime-init/releases/tag/1.2.1).
